services:
  jupyter:
    image: gx/bigquery_example_jupyter
    container_name: gx_bigquery_example_jupyter
    build:
      context: .
      dockerfile: jupyter.Dockerfile
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/creds.json
      BIGQUERY_CONNECTION_STRING: ${BIGQUERY_CONNECTION_STRING}
    ports:
      - "8888:8888"
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/creds.json
      - gx_stores:/gx/gx_stores
    networks:
      - dbnet

  data_docs:
    image: gx/bigquery_data_docs
    container_name: gx_bigquery_data_docs
    build:
      context: .
      dockerfile: data_docs.Dockerfile
    networks:
      - dbnet
    ports:
      - "3000:3000"
    volumes:
      - gx_stores:/gx/gx_stores:ro

networks:
  dbnet:
    driver: bridge

volumes:
  gx_stores:
